import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ViewTracker from "@/components/ViewTracker/ViewTracker";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cyber Awareness Hub",
  description: "Generated by create next app",
  verification: {
    google: "7iBv3brFyyG-SDhptMatuErD9jo0uUPoFSx2J-wbB3o",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ViewTracker />
        {children}
      </body>
    </html>
  );
}
